---
# Source: iheatlab-2.0/templates/web.yaml
apiVersion: v1
kind: Service
metadata:
  name: heat-system-web
  namespace: hundun-prod
  labels:
    app: heat-system-web
    prometheus: nginx-vts
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 9913
      targetPort: 9913
      protocol: TCP
      name: nginx-vts      
  selector:
    app: heat-system-web    
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
---
# Source: iheatlab-2.0/templates/web.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heat-system-web
  namespace: hundun-prod
  labels:
    app: heat-system-web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  selector:
    matchLabels:
      app: heat-system-web
  template:
    metadata:
      labels:
        app: heat-system-web
      annotations:
        prometheus.io/scrape: "true"        
    spec:
      nodeSelector:
        venus: app    
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - heat-system-web
                topologyKey: kubernetes.io/hostname        
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: # 硬策略
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - k8s-node11
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2                 
      imagePullSecrets:
      - name: prod-secret-cr  
      initContainers:
      - name: setsysctl
        image: busybox
        securityContext:
          privileged: true
        command:
        - sh
        - -c
        - |
          sysctl -w net.core.somaxconn=65535
          sysctl -w net.ipv4.tcp_tw_reuse=1
          sysctl -w fs.file-max=1048576      
      containers:
      - name: nginx-vts-exporter
        image: "registry.cn-shanghai.aliyuncs.com/hundun_develop_registry/nginx-vts-exporter:0.10.4"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9913
        resources:
          limits:
            memory: "30Mi"
            cpu: "100m"
          requests:
            memory: "30Mi"
            cpu: "100m"
        livenessProbe:
          failureThreshold: 20
          tcpSocket:
            port: 9913
          initialDelaySeconds: 60
          timeoutSeconds: 60      
      - name: heat-system-web
        image: "hundun-registry-registry.cn-shanghai.cr.aliyuncs.com/hundun_registry/heat-system-web:60-release-23.02.24-demo-560c69b1"
        imagePullPolicy: IfNotPresent      
        volumeMounts:
        - name: waf-config
          mountPath: "/usr/local/nginx/conf/waf/config.lua"
          subPath: config.lua
          readOnly: true          
        resources:
          limits:
            cpu: "0.5"
            memory: "2560Mi"    
          requests:
            memory: "1024Mi"
            cpu: "0.1" 
        ports:
        - containerPort: 80
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit;"]          
        livenessProbe:
          tcpSocket:
            port: 80
      volumes:
      - name: waf-config
        configMap:
          name: wafconfig
